Repository REPfit-Retail-Price-Fit/backend-repfit, pull requests merged in 2022-06, with the labels that each got.

#2 Task akhfzl
  _main/settings.py
  _main/urls.py
  accounts/views.py
  price_predict/__init__.py
  price_predict/admin.py
  price_predict/apps.py
  price_predict/migrations/0001_initial.py
  price_predict/migrations/__init__.py
  price_predict/models.py
  price_predict/schema/__init__.py
  price_predict/schema/default.py
  price_predict/serializers.py
  price_predict/tests.py
  price_predict/urls.py
  price_predict/views.py
  requirement.txt
  result/model_repfit_v1.h5
  result/model_repfit_v1.json
  result/model_repfit_v1_weights.h5
  result/model_repfit_weight_v1.h5
  result/scaler_v2.save
Labels: development:core

#3 fix the name of requirement file into requirements
  requirements.txt
Labels: bug

#6 Enabled Blacklist token app from simplejwt
  _main/settings.py
  _main/views.py
  tokens/serializers.py
  tokens/urls.py
  tokens/views.py
Labels: development:core

#7 branch-predict-ML
  manager/__init__.py
  manager/base.py
  model/model_repfit_v1.h5
  model/model_repfit_v1.json
  model/model_repfit_weight_v1.h5
  model/repfit_scaler.joblib
  price_predict/migrations/0001_initial.py
  price_predict/migrations/0002_stockout.py
  price_predict/models.py
  price_predict/schema/default.py
  price_predict/serializers.py
  price_predict/urls.py
  price_predict/views.py
  result/model_repfit_v1.h5
  result/model_repfit_v1.json
  result/model_repfit_v1_weights.h5
  result/model_repfit_weight_v1.h5
  result/scaler_v2.save
Labels: development:core

#10 make nanoid to be used as user_id
  accounts/migrations/0002_alter_usermodel_id.py
  accounts/models.py
  accounts/views.py
Labels: development:core

#16 fix-them
  price_predict/urls.py
  price_predict/views.py
  tokens/views.py
Labels: development:core

#20 added deployment section into readme
  README.md
  assets/allow-drf-default-port.png
Labels: documentation

#22 problem-solve
  price_predict/urls.py
  price_predict/views.py
Labels: bug
